// <auto-generated />
using System;
using INFRA;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace INFRA.Migrations
{
    [DbContext(typeof(AgroManagerDbContext))]
    [Migration("20260511202229_AddSwinweFkAndIndex")]
    partial class AddSwinweFkAndIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MODEL.AnimalEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DeathDate")
                        .HasColumnType("date");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Origin")
                        .HasColumnType("integer");

                    b.Property<string>("PhotoKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateOnly?>("PurchaseDate")
                        .HasColumnType("date");

                    b.Property<string>("Tag")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("MODEL.BatchEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("MODEL.BatchMemberEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnimalId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("BatchEntryDate")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset?>("BatchExitDate")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExitReason")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId")
                        .IsUnique()
                        .HasFilter("\"BatchExitDate\" IS NULL");

                    b.HasIndex("BatchId");

                    b.HasIndex("AnimalId", "BatchExitDate");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("MODEL.BovineWeight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BovineId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("OccurrenceDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("BovineId", "OccurrenceDate");

                    b.ToTable("BovineWeightRecords", (string)null);
                });

            modelBuilder.Entity("MODEL.MilkEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BovineId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("Liters")
                        .HasColumnType("real");

                    b.Property<DateOnly>("OccurrenceDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BovineId");

                    b.ToTable("MilkRecords", (string)null);
                });

            modelBuilder.Entity("MODEL.ParentageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("BreedingType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FatherFlag")
                        .HasColumnType("integer");

                    b.Property<Guid?>("FatherId")
                        .HasColumnType("uuid");

                    b.Property<int>("MotherFlag")
                        .HasColumnType("integer");

                    b.Property<Guid>("MotherId")
                        .HasColumnType("uuid");

                    b.Property<int>("SurrogateMotherFlag")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SurrogateMotherId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("MODEL.PastureEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Pastures");
                });

            modelBuilder.Entity("MODEL.SwineWeight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("OccurrenceDate")
                        .HasColumnType("date");

                    b.Property<Guid>("SwineId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("SwineId", "OccurrenceDate");

                    b.ToTable("SwineWeightRecords", (string)null);
                });

            modelBuilder.Entity("MODEL.BovineEntity", b =>
                {
                    b.HasBaseType("MODEL.AnimalEntity");

                    b.Property<int?>("Breed")
                        .HasColumnType("integer");

                    b.Property<int?>("CattleType")
                        .HasColumnType("integer");

                    b.Property<int?>("MaritalStatus")
                        .HasColumnType("integer");

                    b.ToTable("Bovines", (string)null);
                });

            modelBuilder.Entity("MODEL.SwineEntity", b =>
                {
                    b.HasBaseType("MODEL.AnimalEntity");

                    b.Property<int?>("Breed")
                        .HasColumnType("integer");

                    b.Property<int?>("PorcType")
                        .HasColumnType("integer");

                    b.ToTable("Swines", (string)null);
                });

            modelBuilder.Entity("MODEL.BovinePastureBatch", b =>
                {
                    b.HasBaseType("MODEL.BatchEntity");

                    b.Property<Guid>("PastureId")
                        .HasColumnType("uuid");

                    b.HasIndex("PastureId");

                    b.ToTable("BovinePastureBatchs", (string)null);
                });

            modelBuilder.Entity("MODEL.SwineBeefBatch", b =>
                {
                    b.HasBaseType("MODEL.BatchEntity");

                    b.ToTable("SwineBeefBatchs", (string)null);
                });

            modelBuilder.Entity("MODEL.BovinePastureMember", b =>
                {
                    b.HasBaseType("MODEL.BatchMemberEntity");

                    b.ToTable("BovinePastureMembers", (string)null);
                });

            modelBuilder.Entity("MODEL.SwineBeefMember", b =>
                {
                    b.HasBaseType("MODEL.BatchMemberEntity");

                    b.ToTable("SwineBeefMembers", (string)null);
                });

            modelBuilder.Entity("MODEL.BovineParentageEntity", b =>
                {
                    b.HasBaseType("MODEL.ParentageEntity");

                    b.HasIndex("FatherId");

                    b.HasIndex("MotherId");

                    b.HasIndex("SurrogateMotherId");

                    b.ToTable("BovineParentages", (string)null);
                });

            modelBuilder.Entity("MODEL.SwineParentageEntity", b =>
                {
                    b.HasBaseType("MODEL.ParentageEntity");

                    b.HasIndex("FatherId");

                    b.HasIndex("MotherId");

                    b.HasIndex("SurrogateMotherId");

                    b.ToTable("SwineParentages", (string)null);
                });

            modelBuilder.Entity("MODEL.BovineWeight", b =>
                {
                    b.HasOne("MODEL.BovineEntity", null)
                        .WithMany()
                        .HasForeignKey("BovineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MODEL.MilkEntity", b =>
                {
                    b.HasOne("MODEL.BovineEntity", null)
                        .WithMany()
                        .HasForeignKey("BovineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MODEL.SwineWeight", b =>
                {
                    b.HasOne("MODEL.SwineEntity", null)
                        .WithMany()
                        .HasForeignKey("SwineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MODEL.BovinePastureBatch", b =>
                {
                    b.HasOne("MODEL.PastureEntity", null)
                        .WithMany()
                        .HasForeignKey("PastureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MODEL.BovinePastureMember", b =>
                {
                    b.HasOne("MODEL.BovineEntity", null)
                        .WithMany()
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MODEL.BovinePastureBatch", null)
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MODEL.SwineBeefMember", b =>
                {
                    b.HasOne("MODEL.SwineEntity", null)
                        .WithMany()
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MODEL.SwineBeefBatch", null)
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MODEL.BovineParentageEntity", b =>
                {
                    b.HasOne("MODEL.BovineEntity", null)
                        .WithMany()
                        .HasForeignKey("FatherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_parentage_bovine_father");

                    b.HasOne("MODEL.BovineEntity", null)
                        .WithOne()
                        .HasForeignKey("MODEL.BovineParentageEntity", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_parentage_bovine_animal");

                    b.HasOne("MODEL.BovineEntity", null)
                        .WithMany()
                        .HasForeignKey("MotherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_parentage_bovine_mother");

                    b.HasOne("MODEL.BovineEntity", null)
                        .WithMany()
                        .HasForeignKey("SurrogateMotherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_parentage_bovine_surrogate");
                });

            modelBuilder.Entity("MODEL.SwineParentageEntity", b =>
                {
                    b.HasOne("MODEL.SwineEntity", null)
                        .WithMany()
                        .HasForeignKey("FatherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_parentage_swine_father");

                    b.HasOne("MODEL.SwineEntity", null)
                        .WithOne()
                        .HasForeignKey("MODEL.SwineParentageEntity", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_parentage_swine_animal");

                    b.HasOne("MODEL.SwineEntity", null)
                        .WithMany()
                        .HasForeignKey("MotherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_parentage_swine_mother");

                    b.HasOne("MODEL.SwineEntity", null)
                        .WithMany()
                        .HasForeignKey("SurrogateMotherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_parentage_swine_surrogate");
                });
#pragma warning restore 612, 618
        }
    }
}
